package com.tasktracker.model;

import jakarta.persistence.*;

@Entity   //marking this class as a JPA entity(i.e...it maps fields to a table)
@Table(name = "tasks") //specifies the table name
public class Task {

    @Id //marking id field as a primary field
    @GeneratedValue(strategy = GenerationType.IDENTITY) //id values will be autogenerated
    private Long id;

    @Column(nullable = false) //marking this field as non-nullable. this field holds some value all the time
    private String title;

    private String description;
    @Column(nullable = false)
    private String status;

    //Constructor
    public Task() {}
    public Task(String title, String description, String status){
        this.title = title;
        this.description = description;
        this.status = status;
    }
    //Getters
    public Long getId(){
        return id;
    }
    public String getTitle(){
        return title;
    }
    public String getDescription(){
        return description;
    }
    public String getStatus(){
        return status;
    }
    //Setters
    public void setId(Long id){
        this.id = id;
    }
    public void setTitle(String title){
        this.title = title;
    }
    public void setDescription(String description){
        this.description = description;
    }
    public void setStatus(String status){
        this.status = status;
    }
}
